In [4]:
#Notebook Created for Checkpoint 04
#Author - Amit Adate

In [5]:
import numpy as np

In [6]:
import tensorflow as tf

In [7]:
import sklearn

In [8]:
corpus_raw = 'He is the king . The king is royal . She is the royal  queen '

In [9]:
#convert to lower case
corpus_raw = corpus_raw.lower()

words = []

# because we don't want to treat . as a word
for word in corpus_raw.split():
    if word != '.':
        words.append(word)

# remove all duplicate words
words = set(words)

word2int = {}
int2word = {}

# gives the total number of unique words
vocab_size = len(words)


for i,word in enumerate(words):
    word2int[word] = i
    int2word[i] = word
    






In [10]:
print(word2int['royal'])

0


In [11]:
# we want to add our sentences as a list of words

# raw sentences is a list of sentences.
raw_sentences = corpus_raw.split('.')
sentences = []


for sentence in raw_sentences:
    sentences.append(sentence.split())

In [12]:
print(sentences)

[['he', 'is', 'the', 'king'], ['the', 'king', 'is', 'royal'], ['she', 'is', 'the', 'royal', 'queen']]


In [13]:
data = []

WINDOW_SIZE = 2

for sentence in sentences:
    for word_index, word in enumerate(sentence):
        for nb_word in sentence[max(word_index - WINDOW_SIZE, 0) : min(word_index + WINDOW_SIZE, len(sentence)) + 1] : 
            if nb_word != word:
                data.append([word, nb_word])

In [14]:
# This basically gives a list of word, word pairs. (we are considering a window size of 2)

print(words)



{'royal', 'the', 'queen', 'is', 'king', 'he', 'she'}


In [15]:
print(sentences)

[['he', 'is', 'the', 'king'], ['the', 'king', 'is', 'royal'], ['she', 'is', 'the', 'royal', 'queen']]


In [16]:
# this is our training data

print(data)
print(len(data))


[['he', 'is'], ['he', 'the'], ['is', 'he'], ['is', 'the'], ['is', 'king'], ['the', 'he'], ['the', 'is'], ['the', 'king'], ['king', 'is'], ['king', 'the'], ['the', 'king'], ['the', 'is'], ['king', 'the'], ['king', 'is'], ['king', 'royal'], ['is', 'the'], ['is', 'king'], ['is', 'royal'], ['royal', 'king'], ['royal', 'is'], ['she', 'is'], ['she', 'the'], ['is', 'she'], ['is', 'the'], ['is', 'royal'], ['the', 'she'], ['the', 'is'], ['the', 'royal'], ['the', 'queen'], ['royal', 'is'], ['royal', 'the'], ['royal', 'queen'], ['queen', 'the'], ['queen', 'royal']]
34


In [17]:
# function to convert numbers to one hot vectors
def to_one_hot(data_point_index, vocab_size):
    temp = np.zeros(vocab_size)
    temp[data_point_index] = 1
    return temp

# input word
x_train = [] 

# output word
y_train = []

for data_word in data:
    x_train.append(to_one_hot(word2int[ data_word[0] ], vocab_size))
    y_train.append(to_one_hot(word2int[ data_word[1] ], vocab_size))
    
# convert them to numpy arrays
x_train = np.asarray(x_train)
y_train = np.asarray(y_train)

In [18]:
print(x_train)

[[0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]


In [19]:
print(x_train.shape, y_train.shape)

(34, 7) (34, 7)


In [20]:
x = tf.placeholder(tf.float32, shape=(None, vocab_size))
y_label = tf.placeholder(tf.float32, shape=(None, vocab_size))

In [21]:
# one can choose their own embedding dimension
EMBEDDING_DIM = 5 

W1 = tf.Variable(tf.random_normal([vocab_size, EMBEDDING_DIM]))

#bias
b1 = tf.Variable(tf.random_normal([EMBEDDING_DIM])) 

hidden_representation = tf.add(tf.matmul(x,W1), b1)

In [22]:
W2 = tf.Variable(tf.random_normal([EMBEDDING_DIM, vocab_size]))

b2 = tf.Variable(tf.random_normal([vocab_size]))

# softmax layer
prediction = tf.nn.softmax(tf.add( tf.matmul(hidden_representation, W2), b2))

In [23]:
#training
sess = tf.Session()
init = tf.global_variables_initializer()

#running the session
sess.run(init) 

# define the loss function:
cross_entropy_loss = tf.reduce_mean(-tf.reduce_sum(y_label * tf.log(prediction), reduction_indices=[1]))

# define the training step:
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy_loss)
n_iters = 10000
# train for n_iter iterations
for _ in range(n_iters):
    sess.run(train_step, feed_dict={x: x_train, y_label: y_train})
    print('loss is : ', sess.run(cross_entropy_loss, feed_dict={x: x_train, y_label: y_train}))

loss is :  3.66595
loss is :  3.4892166
loss is :  3.3382812
loss is :  3.2087364
loss is :  3.0978906
loss is :  3.0036566
loss is :  2.9239812
loss is :  2.8566623
loss is :  2.7994425
loss is :  2.7502031
loss is :  2.707135
loss is :  2.6688106
loss is :  2.6341648
loss is :  2.60243
loss is :  2.5730572
loss is :  2.5456505
loss is :  2.5199158
loss is :  2.4956295
loss is :  2.472612
loss is :  2.4507177
loss is :  2.4298263
loss is :  2.4098346
loss is :  2.390656
loss is :  2.372214
loss is :  2.354445
loss is :  2.337292
loss is :  2.3207061
loss is :  2.3046448
loss is :  2.2890704
loss is :  2.273951
loss is :  2.2592576
loss is :  2.2449646
loss is :  2.2310505
loss is :  2.2174954
loss is :  2.2042806
loss is :  2.1913915
loss is :  2.178813
loss is :  2.166533
loss is :  2.1545393
loss is :  2.1428218
loss is :  2.1313708
loss is :  2.1201766
loss is :  2.1092315
loss is :  2.0985274
loss is :  2.0880566
loss is :  2.0778131
loss is :  2.0677896
loss is :  2.05798
loss is

loss is :  1.3510865
loss is :  1.3509761
loss is :  1.3508669
loss is :  1.3507582
loss is :  1.35065
loss is :  1.3505428
loss is :  1.350436
loss is :  1.3503296
loss is :  1.3502243
loss is :  1.3501196
loss is :  1.3500153
loss is :  1.3499118
loss is :  1.3498089
loss is :  1.3497068
loss is :  1.349605
loss is :  1.3495041
loss is :  1.3494035
loss is :  1.3493038
loss is :  1.3492047
loss is :  1.349106
loss is :  1.3490078
loss is :  1.3489103
loss is :  1.3488137
loss is :  1.3487173
loss is :  1.3486217
loss is :  1.3485265
loss is :  1.3484318
loss is :  1.3483379
loss is :  1.3482443
loss is :  1.3481513
loss is :  1.3480592
loss is :  1.3479673
loss is :  1.3478758
loss is :  1.3477851
loss is :  1.3476948
loss is :  1.347605
loss is :  1.3475158
loss is :  1.347427
loss is :  1.3473388
loss is :  1.347251
loss is :  1.3471639
loss is :  1.3470773
loss is :  1.3469911
loss is :  1.3469054
loss is :  1.34682
loss is :  1.3467352
loss is :  1.346651
loss is :  1.3465672
los

loss is :  1.3311256
loss is :  1.3311086
loss is :  1.3310916
loss is :  1.3310747
loss is :  1.3310578
loss is :  1.3310411
loss is :  1.3310244
loss is :  1.3310077
loss is :  1.3309909
loss is :  1.3309742
loss is :  1.3309578
loss is :  1.3309412
loss is :  1.3309246
loss is :  1.3309083
loss is :  1.3308918
loss is :  1.3308755
loss is :  1.3308592
loss is :  1.330843
loss is :  1.3308268
loss is :  1.3308107
loss is :  1.3307943
loss is :  1.3307785
loss is :  1.3307623
loss is :  1.3307464
loss is :  1.3307304
loss is :  1.3307145
loss is :  1.3306988
loss is :  1.330683
loss is :  1.3306671
loss is :  1.3306513
loss is :  1.3306359
loss is :  1.33062
loss is :  1.3306046
loss is :  1.3305888
loss is :  1.3305733
loss is :  1.330558
loss is :  1.3305426
loss is :  1.3305271
loss is :  1.3305118
loss is :  1.3304964
loss is :  1.3304813
loss is :  1.3304662
loss is :  1.330451
loss is :  1.3304358
loss is :  1.3304205
loss is :  1.3304055
loss is :  1.3303907
loss is :  1.330375

loss is :  1.3260345
loss is :  1.3260292
loss is :  1.326024
loss is :  1.3260183
loss is :  1.3260133
loss is :  1.3260078
loss is :  1.3260027
loss is :  1.3259974
loss is :  1.3259921
loss is :  1.3259869
loss is :  1.3259816
loss is :  1.3259764
loss is :  1.3259709
loss is :  1.3259659
loss is :  1.3259605
loss is :  1.3259554
loss is :  1.32595
loss is :  1.3259449
loss is :  1.3259398
loss is :  1.3259344
loss is :  1.3259295
loss is :  1.3259242
loss is :  1.3259192
loss is :  1.325914
loss is :  1.3259089
loss is :  1.3259039
loss is :  1.3258985
loss is :  1.3258934
loss is :  1.3258884
loss is :  1.3258832
loss is :  1.3258781
loss is :  1.325873
loss is :  1.325868
loss is :  1.3258629
loss is :  1.325858
loss is :  1.3258529
loss is :  1.3258479
loss is :  1.3258427
loss is :  1.3258377
loss is :  1.3258328
loss is :  1.3258277
loss is :  1.3258228
loss is :  1.3258178
loss is :  1.3258128
loss is :  1.3258078
loss is :  1.3258029
loss is :  1.3257979
loss is :  1.3257931

loss is :  1.324153
loss is :  1.3241504
loss is :  1.3241477
loss is :  1.3241452
loss is :  1.3241427
loss is :  1.3241401
loss is :  1.3241376
loss is :  1.324135
loss is :  1.3241324
loss is :  1.3241299
loss is :  1.3241274
loss is :  1.3241248
loss is :  1.3241224
loss is :  1.3241198
loss is :  1.3241173
loss is :  1.3241148
loss is :  1.3241123
loss is :  1.3241098
loss is :  1.3241072
loss is :  1.3241049
loss is :  1.3241023
loss is :  1.3240998
loss is :  1.3240974
loss is :  1.3240948
loss is :  1.3240924
loss is :  1.3240899
loss is :  1.3240874
loss is :  1.3240848
loss is :  1.3240824
loss is :  1.32408
loss is :  1.3240774
loss is :  1.324075
loss is :  1.3240725
loss is :  1.32407
loss is :  1.3240677
loss is :  1.3240651
loss is :  1.3240626
loss is :  1.3240602
loss is :  1.3240577
loss is :  1.3240553
loss is :  1.3240528
loss is :  1.3240503
loss is :  1.3240479
loss is :  1.3240457
loss is :  1.3240432
loss is :  1.3240407
loss is :  1.3240383
loss is :  1.3240359

loss is :  1.3231211
loss is :  1.3231194
loss is :  1.3231182
loss is :  1.3231167
loss is :  1.3231153
loss is :  1.3231138
loss is :  1.3231125
loss is :  1.323111
loss is :  1.3231096
loss is :  1.3231081
loss is :  1.3231068
loss is :  1.3231055
loss is :  1.3231039
loss is :  1.3231025
loss is :  1.3231012
loss is :  1.3230999
loss is :  1.3230983
loss is :  1.3230969
loss is :  1.3230954
loss is :  1.3230942
loss is :  1.3230927
loss is :  1.3230913
loss is :  1.3230898
loss is :  1.3230886
loss is :  1.3230871
loss is :  1.3230857
loss is :  1.3230844
loss is :  1.3230829
loss is :  1.3230815
loss is :  1.3230801
loss is :  1.3230786
loss is :  1.3230773
loss is :  1.3230759
loss is :  1.3230747
loss is :  1.3230733
loss is :  1.3230717
loss is :  1.3230704
loss is :  1.3230691
loss is :  1.3230677
loss is :  1.3230662
loss is :  1.3230649
loss is :  1.3230635
loss is :  1.3230622
loss is :  1.3230608
loss is :  1.3230596
loss is :  1.3230581
loss is :  1.3230566
loss is :  1.3

loss is :  1.3224794
loss is :  1.3224787
loss is :  1.3224777
loss is :  1.3224767
loss is :  1.322476
loss is :  1.3224751
loss is :  1.3224744
loss is :  1.3224735
loss is :  1.3224726
loss is :  1.3224716
loss is :  1.3224708
loss is :  1.32247
loss is :  1.3224692
loss is :  1.3224683
loss is :  1.3224674
loss is :  1.3224666
loss is :  1.3224657
loss is :  1.3224648
loss is :  1.322464
loss is :  1.322463
loss is :  1.3224623
loss is :  1.3224614
loss is :  1.3224603
loss is :  1.3224596
loss is :  1.3224589
loss is :  1.3224579
loss is :  1.322457
loss is :  1.3224562
loss is :  1.3224554
loss is :  1.3224546
loss is :  1.3224535
loss is :  1.3224528
loss is :  1.322452
loss is :  1.3224511
loss is :  1.3224503
loss is :  1.3224493
loss is :  1.3224486
loss is :  1.3224478
loss is :  1.3224468
loss is :  1.322446
loss is :  1.3224452
loss is :  1.3224444
loss is :  1.3224436
loss is :  1.3224427
loss is :  1.3224419
loss is :  1.3224409
loss is :  1.3224403
loss is :  1.3224393


loss is :  1.3220986
loss is :  1.3220979
loss is :  1.3220972
loss is :  1.3220967
loss is :  1.3220961
loss is :  1.3220955
loss is :  1.3220948
loss is :  1.3220943
loss is :  1.3220936
loss is :  1.3220931
loss is :  1.3220925
loss is :  1.3220918
loss is :  1.3220912
loss is :  1.3220909
loss is :  1.32209
loss is :  1.3220896
loss is :  1.3220888
loss is :  1.3220884
loss is :  1.3220878
loss is :  1.3220873
loss is :  1.3220867
loss is :  1.3220859
loss is :  1.3220854
loss is :  1.3220848
loss is :  1.3220842
loss is :  1.3220836
loss is :  1.3220831
loss is :  1.3220825
loss is :  1.3220817
loss is :  1.3220813
loss is :  1.3220805
loss is :  1.32208
loss is :  1.3220795
loss is :  1.322079
loss is :  1.3220783
loss is :  1.3220778
loss is :  1.3220772
loss is :  1.3220766
loss is :  1.322076
loss is :  1.3220754
loss is :  1.3220749
loss is :  1.322074
loss is :  1.3220737
loss is :  1.3220731
loss is :  1.3220725
loss is :  1.322072
loss is :  1.3220713
loss is :  1.3220707


loss is :  1.3218204
loss is :  1.32182
loss is :  1.3218195
loss is :  1.3218191
loss is :  1.3218187
loss is :  1.3218184
loss is :  1.3218179
loss is :  1.3218175
loss is :  1.321817
loss is :  1.3218164
loss is :  1.3218163
loss is :  1.3218157
loss is :  1.3218153
loss is :  1.3218149
loss is :  1.3218145
loss is :  1.3218141
loss is :  1.3218136
loss is :  1.3218132
loss is :  1.3218127
loss is :  1.3218124
loss is :  1.321812
loss is :  1.3218114
loss is :  1.3218111
loss is :  1.3218107
loss is :  1.3218101
loss is :  1.3218098
loss is :  1.3218094
loss is :  1.3218088
loss is :  1.3218085
loss is :  1.3218081
loss is :  1.3218076
loss is :  1.3218071
loss is :  1.3218069
loss is :  1.3218064
loss is :  1.321806
loss is :  1.3218055
loss is :  1.321805
loss is :  1.3218048
loss is :  1.3218043
loss is :  1.3218038
loss is :  1.3218035
loss is :  1.3218031
loss is :  1.3218025
loss is :  1.321802
loss is :  1.3218018
loss is :  1.3218013
loss is :  1.3218008
loss is :  1.3218006

loss is :  1.3216286
loss is :  1.3216282
loss is :  1.3216279
loss is :  1.3216276
loss is :  1.3216271
loss is :  1.3216269
loss is :  1.3216267
loss is :  1.3216262
loss is :  1.3216258
loss is :  1.3216256
loss is :  1.3216254
loss is :  1.321625
loss is :  1.3216246
loss is :  1.3216243
loss is :  1.3216239
loss is :  1.3216237
loss is :  1.3216232
loss is :  1.321623
loss is :  1.3216227
loss is :  1.3216223
loss is :  1.3216219
loss is :  1.3216217
loss is :  1.3216213
loss is :  1.321621
loss is :  1.3216207
loss is :  1.3216202
loss is :  1.32162
loss is :  1.3216199
loss is :  1.3216194
loss is :  1.321619
loss is :  1.3216188
loss is :  1.3216184
loss is :  1.3216181
loss is :  1.3216178
loss is :  1.3216175
loss is :  1.321617
loss is :  1.3216168
loss is :  1.3216164
loss is :  1.3216163
loss is :  1.3216158
loss is :  1.3216155
loss is :  1.3216151
loss is :  1.3216149
loss is :  1.3216145
loss is :  1.3216143
loss is :  1.3216139
loss is :  1.3216137
loss is :  1.3216132

loss is :  1.3214648
loss is :  1.3214643
loss is :  1.3214641
loss is :  1.3214638
loss is :  1.3214636
loss is :  1.3214633
loss is :  1.321463
loss is :  1.3214628
loss is :  1.3214625
loss is :  1.3214624
loss is :  1.321462
loss is :  1.3214617
loss is :  1.3214617
loss is :  1.3214613
loss is :  1.3214611
loss is :  1.3214607
loss is :  1.3214605
loss is :  1.3214602
loss is :  1.32146
loss is :  1.3214598
loss is :  1.3214597
loss is :  1.3214593
loss is :  1.3214592
loss is :  1.3214588
loss is :  1.3214586
loss is :  1.3214583
loss is :  1.321458
loss is :  1.3214579
loss is :  1.3214576
loss is :  1.3214574
loss is :  1.3214571
loss is :  1.3214568
loss is :  1.3214566
loss is :  1.3214563
loss is :  1.3214561
loss is :  1.3214558
loss is :  1.3214556
loss is :  1.3214554
loss is :  1.3214551
loss is :  1.3214549
loss is :  1.3214546
loss is :  1.3214543
loss is :  1.321454
loss is :  1.3214539
loss is :  1.3214537
loss is :  1.3214535
loss is :  1.3214531
loss is :  1.321452

loss is :  1.3213462
loss is :  1.3213458
loss is :  1.3213457
loss is :  1.3213454
loss is :  1.3213453
loss is :  1.3213451
loss is :  1.3213449
loss is :  1.3213447
loss is :  1.3213445
loss is :  1.3213443
loss is :  1.3213439
loss is :  1.3213438
loss is :  1.3213437
loss is :  1.3213434
loss is :  1.3213433
loss is :  1.3213431
loss is :  1.3213428
loss is :  1.3213427
loss is :  1.3213425
loss is :  1.3213422
loss is :  1.321342
loss is :  1.3213419
loss is :  1.3213415
loss is :  1.3213415
loss is :  1.3213413
loss is :  1.321341
loss is :  1.3213408
loss is :  1.3213406
loss is :  1.3213404
loss is :  1.3213402
loss is :  1.3213401
loss is :  1.3213398
loss is :  1.3213396
loss is :  1.3213395
loss is :  1.3213394
loss is :  1.321339
loss is :  1.3213388
loss is :  1.3213387
loss is :  1.3213384
loss is :  1.3213382
loss is :  1.3213379
loss is :  1.3213377
loss is :  1.3213377
loss is :  1.3213373
loss is :  1.3213373
loss is :  1.3213372
loss is :  1.3213369
loss is :  1.321

loss is :  1.3212421
loss is :  1.321242
loss is :  1.3212417
loss is :  1.3212415
loss is :  1.3212414
loss is :  1.3212413
loss is :  1.3212411
loss is :  1.3212408
loss is :  1.3212408
loss is :  1.3212405
loss is :  1.3212404
loss is :  1.3212402
loss is :  1.3212401
loss is :  1.32124
loss is :  1.3212398
loss is :  1.3212396
loss is :  1.3212395
loss is :  1.3212394
loss is :  1.3212392
loss is :  1.321239
loss is :  1.3212388
loss is :  1.3212385
loss is :  1.3212385
loss is :  1.3212384
loss is :  1.3212384
loss is :  1.321238
loss is :  1.3212378
loss is :  1.3212377
loss is :  1.3212374
loss is :  1.3212373
loss is :  1.3212373
loss is :  1.321237
loss is :  1.3212368
loss is :  1.3212367
loss is :  1.3212366
loss is :  1.3212365
loss is :  1.3212364
loss is :  1.3212361
loss is :  1.3212359
loss is :  1.3212359
loss is :  1.3212355
loss is :  1.3212353
loss is :  1.3212352
loss is :  1.3212351
loss is :  1.3212348
loss is :  1.3212348
loss is :  1.3212347
loss is :  1.321234

loss is :  1.3211567
loss is :  1.3211567
loss is :  1.3211565
loss is :  1.3211563
loss is :  1.3211563
loss is :  1.321156
loss is :  1.3211559
loss is :  1.3211558
loss is :  1.3211557
loss is :  1.3211555
loss is :  1.3211553
loss is :  1.3211552
loss is :  1.321155
loss is :  1.3211548
loss is :  1.3211547
loss is :  1.3211546
loss is :  1.3211546
loss is :  1.3211546
loss is :  1.3211542
loss is :  1.3211542
loss is :  1.321154
loss is :  1.3211539
loss is :  1.3211538
loss is :  1.3211535
loss is :  1.3211535
loss is :  1.3211535
loss is :  1.3211533
loss is :  1.321153
loss is :  1.321153
loss is :  1.3211528
loss is :  1.3211527
loss is :  1.3211526
loss is :  1.3211524
loss is :  1.3211523
loss is :  1.3211523
loss is :  1.3211521
loss is :  1.321152
loss is :  1.3211519
loss is :  1.3211517
loss is :  1.3211515
loss is :  1.3211515
loss is :  1.3211513
loss is :  1.3211513
loss is :  1.321151
loss is :  1.3211508
loss is :  1.3211508
loss is :  1.3211507
loss is :  1.3211507

loss is :  1.3210905
loss is :  1.3210902
loss is :  1.3210902
loss is :  1.3210901
loss is :  1.3210901
loss is :  1.3210897
loss is :  1.3210897
loss is :  1.3210896
loss is :  1.3210895
loss is :  1.3210894
loss is :  1.3210893
loss is :  1.3210891
loss is :  1.321089
loss is :  1.321089
loss is :  1.3210889
loss is :  1.3210889
loss is :  1.3210886
loss is :  1.3210886
loss is :  1.3210884
loss is :  1.3210882
loss is :  1.3210881
loss is :  1.3210881
loss is :  1.321088
loss is :  1.3210878
loss is :  1.3210878
loss is :  1.3210878
loss is :  1.3210876
loss is :  1.3210874
loss is :  1.3210874
loss is :  1.3210872
loss is :  1.3210871
loss is :  1.321087
loss is :  1.3210869
loss is :  1.3210868
loss is :  1.3210866
loss is :  1.3210865
loss is :  1.3210864
loss is :  1.3210863
loss is :  1.3210862
loss is :  1.321086
loss is :  1.321086
loss is :  1.3210859
loss is :  1.3210858
loss is :  1.3210857
loss is :  1.3210856
loss is :  1.3210856
loss is :  1.3210853
loss is :  1.321085

loss is :  1.321036
loss is :  1.3210359
loss is :  1.3210359
loss is :  1.3210355
loss is :  1.3210355
loss is :  1.3210354
loss is :  1.3210354
loss is :  1.3210353
loss is :  1.3210351
loss is :  1.321035
loss is :  1.321035
loss is :  1.3210348
loss is :  1.3210348
loss is :  1.3210347
loss is :  1.3210347
loss is :  1.3210344
loss is :  1.3210343
loss is :  1.3210343
loss is :  1.3210342
loss is :  1.3210342
loss is :  1.3210341
loss is :  1.3210341
loss is :  1.3210338
loss is :  1.3210338
loss is :  1.3210337
loss is :  1.3210336
loss is :  1.3210336
loss is :  1.3210334
loss is :  1.3210332
loss is :  1.3210331
loss is :  1.321033
loss is :  1.3210329
loss is :  1.3210329
loss is :  1.3210326
loss is :  1.3210326
loss is :  1.3210326
loss is :  1.3210325
loss is :  1.3210325
loss is :  1.3210324
loss is :  1.3210323
loss is :  1.3210322
loss is :  1.321032
loss is :  1.3210319
loss is :  1.321032
loss is :  1.3210317
loss is :  1.3210317
loss is :  1.3210315
loss is :  1.321031

loss is :  1.3209859
loss is :  1.3209858
loss is :  1.3209857
loss is :  1.3209856
loss is :  1.3209854
loss is :  1.3209854
loss is :  1.3209852
loss is :  1.3209852
loss is :  1.3209851
loss is :  1.320985
loss is :  1.320985
loss is :  1.320985
loss is :  1.3209848
loss is :  1.3209848
loss is :  1.3209848
loss is :  1.3209847
loss is :  1.3209846
loss is :  1.3209845
loss is :  1.3209842
loss is :  1.3209844
loss is :  1.3209842
loss is :  1.320984
loss is :  1.320984
loss is :  1.320984
loss is :  1.3209838
loss is :  1.3209838
loss is :  1.3209838
loss is :  1.3209836
loss is :  1.3209835
loss is :  1.3209834
loss is :  1.3209835
loss is :  1.3209833
loss is :  1.3209832
loss is :  1.320983
loss is :  1.320983
loss is :  1.3209829
loss is :  1.3209829
loss is :  1.3209829
loss is :  1.3209828
loss is :  1.3209827
loss is :  1.3209826
loss is :  1.3209826
loss is :  1.3209826
loss is :  1.3209823
loss is :  1.3209823
loss is :  1.3209821
loss is :  1.320982
loss is :  1.320982
lo

loss is :  1.3209467
loss is :  1.3209467
loss is :  1.3209465
loss is :  1.3209465
loss is :  1.3209465
loss is :  1.3209465
loss is :  1.3209462
loss is :  1.3209461
loss is :  1.320946
loss is :  1.320946
loss is :  1.320946
loss is :  1.3209459
loss is :  1.3209457
loss is :  1.3209456
loss is :  1.3209456
loss is :  1.3209456
loss is :  1.3209455
loss is :  1.3209454
loss is :  1.3209454
loss is :  1.3209454
loss is :  1.320945
loss is :  1.320945
loss is :  1.3209448
loss is :  1.3209449
loss is :  1.3209448
loss is :  1.3209448
loss is :  1.3209448
loss is :  1.3209448
loss is :  1.3209447
loss is :  1.3209448
loss is :  1.3209445
loss is :  1.3209445
loss is :  1.3209444
loss is :  1.3209444
loss is :  1.3209443
loss is :  1.3209442
loss is :  1.3209442
loss is :  1.320944
loss is :  1.320944
loss is :  1.3209438
loss is :  1.3209438
loss is :  1.3209438
loss is :  1.3209436
loss is :  1.3209436
loss is :  1.3209434
loss is :  1.3209434
loss is :  1.3209434
loss is :  1.3209434

loss is :  1.320912
loss is :  1.3209122
loss is :  1.320912
loss is :  1.320912
loss is :  1.3209119
loss is :  1.3209118
loss is :  1.3209118
loss is :  1.3209116
loss is :  1.3209116
loss is :  1.3209114
loss is :  1.3209114
loss is :  1.3209114
loss is :  1.3209113
loss is :  1.3209112
loss is :  1.3209112
loss is :  1.3209112
loss is :  1.3209112
loss is :  1.320911
loss is :  1.3209109
loss is :  1.3209108
loss is :  1.3209109
loss is :  1.3209108
loss is :  1.3209107
loss is :  1.3209107
loss is :  1.3209105
loss is :  1.3209105
loss is :  1.3209105
loss is :  1.3209105
loss is :  1.3209103
loss is :  1.3209103
loss is :  1.3209102
loss is :  1.3209101
loss is :  1.3209101
loss is :  1.32091
loss is :  1.32091
loss is :  1.32091
loss is :  1.32091
loss is :  1.3209097
loss is :  1.3209097
loss is :  1.3209096
loss is :  1.3209097
loss is :  1.3209096
loss is :  1.3209094
loss is :  1.3209094
loss is :  1.3209094
loss is :  1.3209091
loss is :  1.3209091
loss is :  1.3209089
loss

In [24]:
print(sess.run(W1))
print('----------')
print(sess.run(b1))
print('----------')

[[ 1.3879479  -1.081527   -1.318203    0.14716242 -0.5159483 ]
 [-2.1948085   0.9399701  -0.35709336 -0.35625592 -1.041155  ]
 [-1.4808155   0.76531655  0.7082741   1.8950515   1.8676984 ]
 [-0.5565951   1.4014952  -2.0240996   1.8670113   1.6218154 ]
 [-0.8373372  -0.3169073   1.6598439   1.9443327  -0.31976008]
 [-0.20554197  1.3710152   2.5309908   0.80177706  0.3724788 ]
 [ 0.6916704  -0.7876575   1.2131851  -1.5637784   1.0857185 ]]
----------
[ 1.4218148  -0.57837695  0.61008215  0.15654264  0.150565  ]
----------


In [25]:
vectors = sess.run(W1 + b1)

# if you work it out, you will see that it has the same effect as running the node hidden representation

In [26]:
print(vectors)

[[ 2.8097627  -1.659904   -0.7081208   0.30370507 -0.3653833 ]
 [-0.7729937   0.36159313  0.2529888  -0.19971327 -0.89058995]
 [-0.05900073  0.1869396   1.3183563   2.051594    2.0182633 ]
 [ 0.8652197   0.82311827 -1.4140174   2.0235538   1.7723805 ]
 [ 0.5844776  -0.89528424  2.269926    2.1008754  -0.16919509]
 [ 1.2162728   0.79263824  3.141073    0.9583197   0.5230438 ]
 [ 2.1134853  -1.3660345   1.8232672  -1.4072357   1.2362835 ]]


In [27]:
print(vectors[ word2int['queen'] ])


[-0.05900073  0.1869396   1.3183563   2.051594    2.0182633 ]


In [28]:
def euclidean_dist(vec1, vec2):
    return np.sqrt(np.sum((vec1-vec2)**2))

def find_closest(word_index, vectors):
    min_dist = 10000 # to act like positive infinity
    min_index = -1
    query_vector = vectors[word_index]
    for index, vector in enumerate(vectors):
        if euclidean_dist(vector, query_vector) < min_dist and not np.array_equal(vector, query_vector):
            min_dist = euclidean_dist(vector, query_vector)
            min_index = index
    return min_index

In [29]:
print(int2word[find_closest(word2int['king'], vectors)])
print(int2word[find_closest(word2int['queen'], vectors)])
print(int2word[find_closest(word2int['royal'], vectors)])

he
king
she
