In [2]:
#Notebook Created for Checkpoint 04
#Author - Amit Adate

In [3]:
import numpy as np

In [4]:
import tensorflow as tf

In [5]:
import sklearn

In [6]:
corpus_raw = 'He is the king . The king is royal . She is the royal  queen '

In [7]:
#convert to lower case
corpus_raw = corpus_raw.lower()

words = []

# because we don't want to treat . as a word
for word in corpus_raw.split():
    if word != '.':
        words.append(word)

# remove all duplicate words
words = set(words)

word2int = {}
int2word = {}

# gives the total number of unique words
vocab_size = len(words)


for i,word in enumerate(words):
    word2int[word] = i
    int2word[i] = word
    






In [8]:
print(word2int['royal'])

3


In [9]:
# we want to add our sentences as a list of words

# raw sentences is a list of sentences.
raw_sentences = corpus_raw.split('.')
sentences = []


for sentence in raw_sentences:
    sentences.append(sentence.split())

In [10]:
print(sentences)

[['he', 'is', 'the', 'king'], ['the', 'king', 'is', 'royal'], ['she', 'is', 'the', 'royal', 'queen']]


In [11]:
data = []

WINDOW_SIZE = 2

for sentence in sentences:
    for word_index, word in enumerate(sentence):
        for nb_word in sentence[max(word_index - WINDOW_SIZE, 0) : min(word_index + WINDOW_SIZE, len(sentence)) + 1] : 
            if nb_word != word:
                data.append([word, nb_word])

In [12]:
# This basically gives a list of word, word pairs. (we are considering a window size of 2)

print(words)



{'king', 'she', 'he', 'royal', 'queen', 'the', 'is'}


In [13]:
print(sentences)

[['he', 'is', 'the', 'king'], ['the', 'king', 'is', 'royal'], ['she', 'is', 'the', 'royal', 'queen']]


In [14]:
# this is our training data

print(data)
print(len(data))


[['he', 'is'], ['he', 'the'], ['is', 'he'], ['is', 'the'], ['is', 'king'], ['the', 'he'], ['the', 'is'], ['the', 'king'], ['king', 'is'], ['king', 'the'], ['the', 'king'], ['the', 'is'], ['king', 'the'], ['king', 'is'], ['king', 'royal'], ['is', 'the'], ['is', 'king'], ['is', 'royal'], ['royal', 'king'], ['royal', 'is'], ['she', 'is'], ['she', 'the'], ['is', 'she'], ['is', 'the'], ['is', 'royal'], ['the', 'she'], ['the', 'is'], ['the', 'royal'], ['the', 'queen'], ['royal', 'is'], ['royal', 'the'], ['royal', 'queen'], ['queen', 'the'], ['queen', 'royal']]
34


In [15]:
# function to convert numbers to one hot vectors
def to_one_hot(data_point_index, vocab_size):
    temp = np.zeros(vocab_size)
    temp[data_point_index] = 1
    return temp

# input word
x_train = [] 

# output word
y_train = []

for data_word in data:
    x_train.append(to_one_hot(word2int[ data_word[0] ], vocab_size))
    y_train.append(to_one_hot(word2int[ data_word[1] ], vocab_size))
    
# convert them to numpy arrays
x_train = np.asarray(x_train)
y_train = np.asarray(y_train)

In [16]:
print(x_train)

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]


In [17]:
print(x_train.shape, y_train.shape)

(34, 7) (34, 7)


In [18]:
x = tf.placeholder(tf.float32, shape=(None, vocab_size))
y_label = tf.placeholder(tf.float32, shape=(None, vocab_size))

In [19]:
# one can choose their own embedding dimension
EMBEDDING_DIM = 5 

W1 = tf.Variable(tf.random_normal([vocab_size, EMBEDDING_DIM]))

#bias
b1 = tf.Variable(tf.random_normal([EMBEDDING_DIM])) 

hidden_representation = tf.add(tf.matmul(x,W1), b1)

In [20]:
W2 = tf.Variable(tf.random_normal([EMBEDDING_DIM, vocab_size]))

b2 = tf.Variable(tf.random_normal([vocab_size]))

# softmax layer
prediction = tf.nn.softmax(tf.add( tf.matmul(hidden_representation, W2), b2))

In [21]:
#training
sess = tf.Session()
init = tf.global_variables_initializer()

#running the session
sess.run(init) 

# define the loss function:
cross_entropy_loss = tf.reduce_mean(-tf.reduce_sum(y_label * tf.log(prediction), reduction_indices=[1]))

# define the training step:
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy_loss)
n_iters = 10000
# train for n_iter iterations
for _ in range(n_iters):
    sess.run(train_step, feed_dict={x: x_train, y_label: y_train})
    print('loss is : ', sess.run(cross_entropy_loss, feed_dict={x: x_train, y_label: y_train}))

loss is :  5.263432
loss is :  4.8428626
loss is :  4.49991
loss is :  4.2127953
loss is :  3.969127
loss is :  3.760403
loss is :  3.580154
loss is :  3.4232922
loss is :  3.2858088
loss is :  3.1645565
loss is :  3.0570545
loss is :  2.9613225
loss is :  2.875744
loss is :  2.7989702
loss is :  2.7298543
loss is :  2.6674092
loss is :  2.6107812
loss is :  2.5592308
loss is :  2.512118
loss is :  2.468893
loss is :  2.4290826
loss is :  2.3922842
loss is :  2.3581543
loss is :  2.3263998
loss is :  2.296771
loss is :  2.2690535
loss is :  2.2430632
loss is :  2.21864
loss is :  2.195645
loss is :  2.173956
loss is :  2.1534636
loss is :  2.1340733
loss is :  2.1156979
loss is :  2.0982609
loss is :  2.0816915
loss is :  2.065927
loss is :  2.05091
loss is :  2.0365882
loss is :  2.0229132
loss is :  2.0098422
loss is :  1.9973342
loss is :  1.9853526
loss is :  1.9738646
loss is :  1.9628379
loss is :  1.9522445
loss is :  1.9420581
loss is :  1.9322543
loss is :  1.9228107
loss is :

loss is :  1.3852382
loss is :  1.384962
loss is :  1.3846871
loss is :  1.3844141
loss is :  1.3841424
loss is :  1.3838722
loss is :  1.3836036
loss is :  1.3833364
loss is :  1.3830708
loss is :  1.3828064
loss is :  1.3825438
loss is :  1.3822824
loss is :  1.3820226
loss is :  1.3817642
loss is :  1.3815072
loss is :  1.3812515
loss is :  1.3809974
loss is :  1.3807447
loss is :  1.3804933
loss is :  1.3802433
loss is :  1.3799946
loss is :  1.3797475
loss is :  1.3795018
loss is :  1.3792572
loss is :  1.379014
loss is :  1.3787721
loss is :  1.3785317
loss is :  1.3782927
loss is :  1.3780549
loss is :  1.3778183
loss is :  1.377583
loss is :  1.3773493
loss is :  1.3771166
loss is :  1.3768853
loss is :  1.3766551
loss is :  1.3764263
loss is :  1.3761989
loss is :  1.3759725
loss is :  1.3757476
loss is :  1.3755237
loss is :  1.375301
loss is :  1.3750798
loss is :  1.3748597
loss is :  1.3746407
loss is :  1.3744229
loss is :  1.3742063
loss is :  1.3739909
loss is :  1.3737

loss is :  1.3379053
loss is :  1.337866
loss is :  1.3378266
loss is :  1.3377874
loss is :  1.3377485
loss is :  1.3377094
loss is :  1.3376708
loss is :  1.3376323
loss is :  1.3375938
loss is :  1.3375555
loss is :  1.3375174
loss is :  1.3374794
loss is :  1.3374414
loss is :  1.3374037
loss is :  1.3373661
loss is :  1.3373286
loss is :  1.3372912
loss is :  1.337254
loss is :  1.337217
loss is :  1.3371801
loss is :  1.3371433
loss is :  1.3371066
loss is :  1.3370701
loss is :  1.3370336
loss is :  1.3369974
loss is :  1.3369613
loss is :  1.3369254
loss is :  1.3368894
loss is :  1.3368539
loss is :  1.336818
loss is :  1.3367826
loss is :  1.3367473
loss is :  1.336712
loss is :  1.3366768
loss is :  1.3366419
loss is :  1.336607
loss is :  1.3365723
loss is :  1.3365376
loss is :  1.3365033
loss is :  1.3364688
loss is :  1.3364346
loss is :  1.3364005
loss is :  1.3363665
loss is :  1.3363328
loss is :  1.336299
loss is :  1.3362652
loss is :  1.3362317
loss is :  1.3361983

loss is :  1.3283588
loss is :  1.3283486
loss is :  1.3283381
loss is :  1.3283279
loss is :  1.3283175
loss is :  1.3283073
loss is :  1.328297
loss is :  1.3282868
loss is :  1.3282768
loss is :  1.3282666
loss is :  1.3282564
loss is :  1.3282462
loss is :  1.3282362
loss is :  1.3282262
loss is :  1.3282161
loss is :  1.3282061
loss is :  1.328196
loss is :  1.3281862
loss is :  1.3281761
loss is :  1.3281662
loss is :  1.3281564
loss is :  1.3281466
loss is :  1.3281367
loss is :  1.3281267
loss is :  1.3281169
loss is :  1.328107
loss is :  1.3280973
loss is :  1.3280876
loss is :  1.3280779
loss is :  1.3280683
loss is :  1.3280584
loss is :  1.3280487
loss is :  1.328039
loss is :  1.3280294
loss is :  1.3280199
loss is :  1.3280103
loss is :  1.3280007
loss is :  1.3279912
loss is :  1.3279818
loss is :  1.3279722
loss is :  1.3279626
loss is :  1.3279533
loss is :  1.3279438
loss is :  1.3279344
loss is :  1.327925
loss is :  1.3279157
loss is :  1.3279063
loss is :  1.32789

loss is :  1.3250345
loss is :  1.3250306
loss is :  1.3250265
loss is :  1.3250226
loss is :  1.3250189
loss is :  1.3250147
loss is :  1.3250108
loss is :  1.325007
loss is :  1.3250029
loss is :  1.3249989
loss is :  1.3249949
loss is :  1.3249911
loss is :  1.3249872
loss is :  1.3249832
loss is :  1.3249793
loss is :  1.3249755
loss is :  1.3249714
loss is :  1.3249677
loss is :  1.3249637
loss is :  1.3249599
loss is :  1.324956
loss is :  1.3249521
loss is :  1.3249483
loss is :  1.3249445
loss is :  1.3249407
loss is :  1.3249369
loss is :  1.324933
loss is :  1.3249292
loss is :  1.3249254
loss is :  1.3249216
loss is :  1.3249178
loss is :  1.324914
loss is :  1.3249102
loss is :  1.3249063
loss is :  1.3249025
loss is :  1.3248987
loss is :  1.3248949
loss is :  1.3248911
loss is :  1.3248874
loss is :  1.3248835
loss is :  1.3248798
loss is :  1.324876
loss is :  1.3248724
loss is :  1.3248688
loss is :  1.324865
loss is :  1.3248612
loss is :  1.3248575
loss is :  1.324853

loss is :  1.3235354
loss is :  1.3235333
loss is :  1.3235314
loss is :  1.3235295
loss is :  1.3235275
loss is :  1.3235255
loss is :  1.3235235
loss is :  1.3235216
loss is :  1.3235197
loss is :  1.3235178
loss is :  1.3235159
loss is :  1.323514
loss is :  1.3235118
loss is :  1.3235099
loss is :  1.323508
loss is :  1.3235061
loss is :  1.3235042
loss is :  1.3235021
loss is :  1.3235003
loss is :  1.3234984
loss is :  1.3234965
loss is :  1.3234944
loss is :  1.3234925
loss is :  1.3234905
loss is :  1.3234887
loss is :  1.3234868
loss is :  1.3234848
loss is :  1.3234829
loss is :  1.323481
loss is :  1.323479
loss is :  1.3234771
loss is :  1.3234752
loss is :  1.3234733
loss is :  1.3234714
loss is :  1.3234696
loss is :  1.3234677
loss is :  1.3234658
loss is :  1.3234639
loss is :  1.323462
loss is :  1.32346
loss is :  1.3234582
loss is :  1.3234564
loss is :  1.3234544
loss is :  1.3234526
loss is :  1.3234508
loss is :  1.3234488
loss is :  1.323447
loss is :  1.3234448


loss is :  1.3227069
loss is :  1.3227056
loss is :  1.3227046
loss is :  1.3227034
loss is :  1.3227023
loss is :  1.3227013
loss is :  1.3227
loss is :  1.3226991
loss is :  1.3226979
loss is :  1.3226968
loss is :  1.3226957
loss is :  1.3226945
loss is :  1.3226933
loss is :  1.3226922
loss is :  1.3226912
loss is :  1.32269
loss is :  1.3226888
loss is :  1.3226877
loss is :  1.3226867
loss is :  1.3226856
loss is :  1.3226843
loss is :  1.3226833
loss is :  1.3226824
loss is :  1.3226812
loss is :  1.32268
loss is :  1.3226789
loss is :  1.3226779
loss is :  1.3226767
loss is :  1.3226756
loss is :  1.3226746
loss is :  1.3226733
loss is :  1.3226724
loss is :  1.3226712
loss is :  1.32267
loss is :  1.322669
loss is :  1.3226678
loss is :  1.3226668
loss is :  1.3226657
loss is :  1.3226647
loss is :  1.3226634
loss is :  1.3226625
loss is :  1.3226613
loss is :  1.3226602
loss is :  1.3226591
loss is :  1.3226582
loss is :  1.3226571
loss is :  1.3226559
loss is :  1.3226547
lo

loss is :  1.322268
loss is :  1.3222672
loss is :  1.3222666
loss is :  1.3222657
loss is :  1.3222649
loss is :  1.3222642
loss is :  1.3222635
loss is :  1.3222625
loss is :  1.3222618
loss is :  1.322261
loss is :  1.3222603
loss is :  1.3222597
loss is :  1.3222588
loss is :  1.322258
loss is :  1.3222572
loss is :  1.3222566
loss is :  1.3222556
loss is :  1.322255
loss is :  1.3222543
loss is :  1.3222535
loss is :  1.3222529
loss is :  1.322252
loss is :  1.3222513
loss is :  1.3222505
loss is :  1.3222497
loss is :  1.3222489
loss is :  1.3222482
loss is :  1.3222475
loss is :  1.3222467
loss is :  1.3222458
loss is :  1.3222452
loss is :  1.3222444
loss is :  1.3222437
loss is :  1.322243
loss is :  1.3222423
loss is :  1.3222415
loss is :  1.3222407
loss is :  1.3222399
loss is :  1.3222392
loss is :  1.3222383
loss is :  1.3222377
loss is :  1.3222371
loss is :  1.3222363
loss is :  1.3222356
loss is :  1.3222347
loss is :  1.322234
loss is :  1.3222332
loss is :  1.3222324

loss is :  1.3220009
loss is :  1.3220003
loss is :  1.3219998
loss is :  1.3219992
loss is :  1.3219986
loss is :  1.321998
loss is :  1.3219974
loss is :  1.3219969
loss is :  1.3219962
loss is :  1.3219957
loss is :  1.3219951
loss is :  1.3219944
loss is :  1.3219938
loss is :  1.3219935
loss is :  1.3219929
loss is :  1.3219923
loss is :  1.3219917
loss is :  1.3219911
loss is :  1.3219905
loss is :  1.32199
loss is :  1.3219895
loss is :  1.3219887
loss is :  1.3219882
loss is :  1.3219877
loss is :  1.3219872
loss is :  1.3219864
loss is :  1.321986
loss is :  1.3219854
loss is :  1.3219849
loss is :  1.3219843
loss is :  1.3219837
loss is :  1.3219831
loss is :  1.3219825
loss is :  1.321982
loss is :  1.3219814
loss is :  1.3219808
loss is :  1.3219802
loss is :  1.3219798
loss is :  1.3219792
loss is :  1.3219787
loss is :  1.3219781
loss is :  1.3219774
loss is :  1.3219769
loss is :  1.3219764
loss is :  1.3219757
loss is :  1.3219752
loss is :  1.3219746
loss is :  1.32197

loss is :  1.3217647
loss is :  1.3217641
loss is :  1.3217636
loss is :  1.3217632
loss is :  1.3217629
loss is :  1.3217623
loss is :  1.321762
loss is :  1.3217615
loss is :  1.3217611
loss is :  1.3217605
loss is :  1.3217603
loss is :  1.3217598
loss is :  1.3217592
loss is :  1.321759
loss is :  1.3217586
loss is :  1.3217582
loss is :  1.3217577
loss is :  1.3217573
loss is :  1.3217568
loss is :  1.3217564
loss is :  1.3217559
loss is :  1.3217554
loss is :  1.3217552
loss is :  1.3217546
loss is :  1.3217542
loss is :  1.3217537
loss is :  1.3217534
loss is :  1.321753
loss is :  1.3217527
loss is :  1.3217521
loss is :  1.3217517
loss is :  1.3217512
loss is :  1.3217509
loss is :  1.3217504
loss is :  1.32175
loss is :  1.3217497
loss is :  1.3217492
loss is :  1.3217487
loss is :  1.3217484
loss is :  1.3217478
loss is :  1.3217475
loss is :  1.3217471
loss is :  1.3217467
loss is :  1.3217461
loss is :  1.3217459
loss is :  1.3217454
loss is :  1.321745
loss is :  1.321744

loss is :  1.3215656
loss is :  1.3215653
loss is :  1.3215649
loss is :  1.3215647
loss is :  1.3215643
loss is :  1.3215641
loss is :  1.3215637
loss is :  1.3215635
loss is :  1.321563
loss is :  1.3215628
loss is :  1.3215624
loss is :  1.3215619
loss is :  1.3215618
loss is :  1.3215615
loss is :  1.3215611
loss is :  1.3215609
loss is :  1.3215605
loss is :  1.3215601
loss is :  1.3215599
loss is :  1.3215597
loss is :  1.3215591
loss is :  1.321559
loss is :  1.3215586
loss is :  1.3215584
loss is :  1.321558
loss is :  1.3215575
loss is :  1.3215573
loss is :  1.321557
loss is :  1.3215567
loss is :  1.3215564
loss is :  1.321556
loss is :  1.3215557
loss is :  1.3215555
loss is :  1.3215551
loss is :  1.3215548
loss is :  1.3215545
loss is :  1.3215542
loss is :  1.3215538
loss is :  1.3215533
loss is :  1.3215532
loss is :  1.321553
loss is :  1.3215526
loss is :  1.3215523
loss is :  1.321552
loss is :  1.3215516
loss is :  1.3215513
loss is :  1.3215512
loss is :  1.3215507

loss is :  1.321439
loss is :  1.3214388
loss is :  1.3214384
loss is :  1.3214383
loss is :  1.321438
loss is :  1.3214377
loss is :  1.3214374
loss is :  1.321437
loss is :  1.3214369
loss is :  1.3214368
loss is :  1.3214365
loss is :  1.321436
loss is :  1.3214358
loss is :  1.3214357
loss is :  1.3214353
loss is :  1.3214351
loss is :  1.3214349
loss is :  1.3214346
loss is :  1.3214344
loss is :  1.321434
loss is :  1.3214337
loss is :  1.3214335
loss is :  1.3214333
loss is :  1.3214331
loss is :  1.3214328
loss is :  1.3214326
loss is :  1.3214324
loss is :  1.321432
loss is :  1.3214318
loss is :  1.3214315
loss is :  1.3214312
loss is :  1.3214309
loss is :  1.3214308
loss is :  1.3214304
loss is :  1.3214302
loss is :  1.32143
loss is :  1.3214296
loss is :  1.3214294
loss is :  1.3214291
loss is :  1.321429
loss is :  1.3214287
loss is :  1.3214284
loss is :  1.3214282
loss is :  1.3214278
loss is :  1.3214276
loss is :  1.3214273
loss is :  1.3214273
loss is :  1.321427
lo

loss is :  1.3213329
loss is :  1.3213328
loss is :  1.3213326
loss is :  1.3213323
loss is :  1.321332
loss is :  1.321332
loss is :  1.3213319
loss is :  1.3213316
loss is :  1.3213313
loss is :  1.321331
loss is :  1.321331
loss is :  1.3213308
loss is :  1.3213304
loss is :  1.3213302
loss is :  1.3213301
loss is :  1.3213298
loss is :  1.3213296
loss is :  1.3213295
loss is :  1.3213292
loss is :  1.3213291
loss is :  1.3213288
loss is :  1.3213286
loss is :  1.3213283
loss is :  1.3213282
loss is :  1.3213279
loss is :  1.3213277
loss is :  1.3213276
loss is :  1.3213273
loss is :  1.3213271
loss is :  1.3213269
loss is :  1.3213267
loss is :  1.3213265
loss is :  1.3213263
loss is :  1.3213261
loss is :  1.321326
loss is :  1.3213255
loss is :  1.3213253
loss is :  1.3213253
loss is :  1.321325
loss is :  1.3213247
loss is :  1.3213245
loss is :  1.3213243
loss is :  1.3213243
loss is :  1.3213241
loss is :  1.3213236
loss is :  1.3213235
loss is :  1.3213234
loss is :  1.321323

loss is :  1.3212433
loss is :  1.3212432
loss is :  1.3212428
loss is :  1.3212428
loss is :  1.3212426
loss is :  1.3212423
loss is :  1.3212423
loss is :  1.3212421
loss is :  1.3212419
loss is :  1.3212419
loss is :  1.3212416
loss is :  1.3212413
loss is :  1.3212413
loss is :  1.321241
loss is :  1.3212408
loss is :  1.3212407
loss is :  1.3212405
loss is :  1.3212404
loss is :  1.3212403
loss is :  1.3212401
loss is :  1.3212398
loss is :  1.3212395
loss is :  1.3212395
loss is :  1.3212392
loss is :  1.3212391
loss is :  1.3212389
loss is :  1.3212386
loss is :  1.3212385
loss is :  1.3212385
loss is :  1.3212383
loss is :  1.3212382
loss is :  1.3212379
loss is :  1.3212377
loss is :  1.3212376
loss is :  1.3212373
loss is :  1.3212372
loss is :  1.3212371
loss is :  1.3212368
loss is :  1.3212366
loss is :  1.3212366
loss is :  1.3212364
loss is :  1.3212361
loss is :  1.321236
loss is :  1.3212359
loss is :  1.3212357
loss is :  1.3212354
loss is :  1.3212352
loss is :  1.32

loss is :  1.3211557
loss is :  1.3211555
loss is :  1.3211554
loss is :  1.3211553
loss is :  1.3211552
loss is :  1.3211551
loss is :  1.3211548
loss is :  1.3211547
loss is :  1.3211546
loss is :  1.3211545
loss is :  1.3211544
loss is :  1.3211542
loss is :  1.321154
loss is :  1.3211539
loss is :  1.3211538
loss is :  1.3211536
loss is :  1.3211534
loss is :  1.3211533
loss is :  1.321153
loss is :  1.321153
loss is :  1.3211529
loss is :  1.3211528
loss is :  1.3211527
loss is :  1.3211524
loss is :  1.3211523
loss is :  1.3211522
loss is :  1.3211521
loss is :  1.3211519
loss is :  1.3211519
loss is :  1.3211516
loss is :  1.3211515
loss is :  1.3211513
loss is :  1.321151
loss is :  1.3211511
loss is :  1.3211508
loss is :  1.3211508
loss is :  1.3211505
loss is :  1.3211505
loss is :  1.3211504
loss is :  1.3211503
loss is :  1.32115
loss is :  1.32115
loss is :  1.3211497
loss is :  1.3211497
loss is :  1.3211495
loss is :  1.3211495
loss is :  1.3211491
loss is :  1.321149
l

loss is :  1.3210825
loss is :  1.3210824
loss is :  1.3210821
loss is :  1.3210821
loss is :  1.321082
loss is :  1.321082
loss is :  1.3210818
loss is :  1.3210818
loss is :  1.3210814
loss is :  1.3210814
loss is :  1.3210812
loss is :  1.321081
loss is :  1.3210809
loss is :  1.3210809
loss is :  1.3210809
loss is :  1.3210807
loss is :  1.3210806
loss is :  1.3210803
loss is :  1.3210803
loss is :  1.3210802
loss is :  1.3210802
loss is :  1.32108
loss is :  1.3210799
loss is :  1.3210797
loss is :  1.3210796
loss is :  1.3210796
loss is :  1.3210794
loss is :  1.3210793
loss is :  1.3210791
loss is :  1.321079
loss is :  1.3210789
loss is :  1.3210788
loss is :  1.3210785
loss is :  1.3210784
loss is :  1.3210784
loss is :  1.3210783
loss is :  1.3210781
loss is :  1.3210781
loss is :  1.3210781
loss is :  1.3210778
loss is :  1.3210778
loss is :  1.3210777
loss is :  1.3210776
loss is :  1.3210773
loss is :  1.3210772
loss is :  1.3210771
loss is :  1.321077
loss is :  1.321077


loss is :  1.3210227
loss is :  1.3210226
loss is :  1.3210225
loss is :  1.3210226
loss is :  1.3210224
loss is :  1.3210222
loss is :  1.321022
loss is :  1.321022
loss is :  1.3210219
loss is :  1.3210219
loss is :  1.3210218
loss is :  1.3210217
loss is :  1.3210214
loss is :  1.3210214
loss is :  1.3210212
loss is :  1.3210211
loss is :  1.3210211
loss is :  1.3210211
loss is :  1.321021
loss is :  1.321021
loss is :  1.3210208
loss is :  1.3210206
loss is :  1.3210206
loss is :  1.3210206
loss is :  1.3210204
loss is :  1.3210202
loss is :  1.3210201
loss is :  1.3210201
loss is :  1.32102
loss is :  1.3210199
loss is :  1.3210196
loss is :  1.3210195
loss is :  1.3210195
loss is :  1.3210194
loss is :  1.3210193
loss is :  1.3210193
loss is :  1.3210192
loss is :  1.3210192
loss is :  1.3210189
loss is :  1.3210188
loss is :  1.3210188
loss is :  1.3210188
loss is :  1.3210186
loss is :  1.3210186
loss is :  1.3210185
loss is :  1.3210183
loss is :  1.321018
loss is :  1.321018


loss is :  1.3209745
loss is :  1.3209743
loss is :  1.3209742
loss is :  1.3209741
loss is :  1.3209741
loss is :  1.3209739
loss is :  1.3209738
loss is :  1.3209738
loss is :  1.3209736
loss is :  1.3209735
loss is :  1.3209735
loss is :  1.3209734
loss is :  1.3209734
loss is :  1.3209734
loss is :  1.3209734
loss is :  1.3209732
loss is :  1.320973
loss is :  1.3209729
loss is :  1.3209728
loss is :  1.3209727
loss is :  1.3209727
loss is :  1.3209726
loss is :  1.3209726
loss is :  1.3209724
loss is :  1.3209722
loss is :  1.3209722
loss is :  1.3209722
loss is :  1.3209721
loss is :  1.320972
loss is :  1.3209718
loss is :  1.3209717
loss is :  1.3209717
loss is :  1.3209717
loss is :  1.3209716
loss is :  1.3209715
loss is :  1.3209715
loss is :  1.3209713
loss is :  1.3209713
loss is :  1.3209711
loss is :  1.3209711
loss is :  1.320971
loss is :  1.320971
loss is :  1.3209709
loss is :  1.3209709
loss is :  1.3209705
loss is :  1.3209707
loss is :  1.3209704
loss is :  1.3209

loss is :  1.3209307
loss is :  1.3209306
loss is :  1.3209306
loss is :  1.3209305
loss is :  1.3209304
loss is :  1.3209304
loss is :  1.3209304
loss is :  1.3209302
loss is :  1.3209301
loss is :  1.3209301
loss is :  1.32093
loss is :  1.3209298
loss is :  1.3209298
loss is :  1.3209298
loss is :  1.3209295
loss is :  1.3209295
loss is :  1.3209295
loss is :  1.3209295
loss is :  1.3209294
loss is :  1.3209294
loss is :  1.3209294
loss is :  1.3209292
loss is :  1.3209292
loss is :  1.320929
loss is :  1.320929
loss is :  1.3209288
loss is :  1.3209288
loss is :  1.3209287
loss is :  1.3209287
loss is :  1.3209286
loss is :  1.3209286
loss is :  1.3209286
loss is :  1.3209282
loss is :  1.3209282
loss is :  1.3209282
loss is :  1.3209281
loss is :  1.3209281
loss is :  1.320928
loss is :  1.3209279
loss is :  1.3209279
loss is :  1.3209277
loss is :  1.3209277
loss is :  1.3209276
loss is :  1.3209276
loss is :  1.3209274
loss is :  1.3209275
loss is :  1.3209275
loss is :  1.32092

loss is :  1.3208942
loss is :  1.3208941
loss is :  1.3208941
loss is :  1.320894
loss is :  1.3208939
loss is :  1.3208939
loss is :  1.3208938
loss is :  1.3208936
loss is :  1.3208938
loss is :  1.3208936
loss is :  1.3208936
loss is :  1.3208935
loss is :  1.3208934
loss is :  1.3208934
loss is :  1.3208933
loss is :  1.3208933
loss is :  1.3208932
loss is :  1.3208932
loss is :  1.3208932
loss is :  1.3208932
loss is :  1.3208929
loss is :  1.3208929
loss is :  1.3208929
loss is :  1.3208928
loss is :  1.3208927
loss is :  1.3208927
loss is :  1.3208925
loss is :  1.3208925
loss is :  1.3208923
loss is :  1.3208923
loss is :  1.3208923
loss is :  1.3208923
loss is :  1.3208921
loss is :  1.3208921
loss is :  1.3208921
loss is :  1.320892
loss is :  1.3208919
loss is :  1.3208919
loss is :  1.3208917
loss is :  1.3208917
loss is :  1.3208916
loss is :  1.3208915
loss is :  1.3208915
loss is :  1.3208915
loss is :  1.3208914
loss is :  1.3208914
loss is :  1.3208914
loss is :  1.32

loss is :  1.3208619
loss is :  1.3208619
loss is :  1.3208619
loss is :  1.3208619
loss is :  1.3208618
loss is :  1.3208617
loss is :  1.3208616
loss is :  1.3208616
loss is :  1.3208613
loss is :  1.3208613
loss is :  1.3208613
loss is :  1.3208613
loss is :  1.3208613
loss is :  1.3208612
loss is :  1.3208611
loss is :  1.3208611
loss is :  1.3208611
loss is :  1.3208611
loss is :  1.3208609
loss is :  1.3208609


In [22]:
print(sess.run(W1))
print('----------')
print(sess.run(b1))
print('----------')

[[ 2.6452687  -0.8260903   0.45839489  0.26931053  0.8944715 ]
 [ 0.8908427  -2.9600804  -0.07559364  0.8534973   0.37443197]
 [-0.8106049  -1.7877455  -1.3932239   0.9973121  -0.9308873 ]
 [ 0.23493573  1.0799878  -1.148737    0.9862164  -1.1525995 ]
 [ 0.62183195 -1.3209856   0.77322716 -0.4215253   2.6179886 ]
 [-0.08380945  1.0155262   2.445667   -0.12746243 -1.3530988 ]
 [-2.0373182  -0.5166945   1.1287745  -0.04390391  1.891917  ]]
----------
[-0.23816933 -0.10936169 -0.99804753 -1.9566057  -0.88557506]
----------


In [23]:
vectors = sess.run(W1 + b1)

# if you work it out, you will see that it has the same effect as running the node hidden representation

In [24]:
print(vectors)

[[ 2.4070992  -0.935452   -0.53965265 -1.6872952   0.00889647]
 [ 0.65267336 -3.069442   -1.0736412  -1.1031084  -0.5111431 ]
 [-1.0487742  -1.8971071  -2.3912714  -0.95929354 -1.8164623 ]
 [-0.0032336   0.97062606 -2.1467845  -0.97038925 -2.0381746 ]
 [ 0.38366264 -1.4303472  -0.22482038 -2.378131    1.7324135 ]
 [-0.32197878  0.90616447  1.4476194  -2.084068   -2.2386737 ]
 [-2.2754877  -0.6260562   0.130727   -2.0005095   1.0063419 ]]


In [25]:
print(vectors[ word2int['queen'] ])


[ 0.38366264 -1.4303472  -0.22482038 -2.378131    1.7324135 ]


In [26]:
def euclidean_dist(vec1, vec2):
    return np.sqrt(np.sum((vec1-vec2)**2))

def find_closest(word_index, vectors):
    min_dist = 10000 # to act like positive infinity
    min_index = -1
    query_vector = vectors[word_index]
    for index, vector in enumerate(vectors):
        if euclidean_dist(vector, query_vector) < min_dist and not np.array_equal(vector, query_vector):
            min_dist = euclidean_dist(vector, query_vector)
            min_index = index
    return min_index

In [27]:
print(int2word[find_closest(word2int['king'], vectors)])
print(int2word[find_closest(word2int['queen'], vectors)])
print(int2word[find_closest(word2int['royal'], vectors)])

queen
king
he


In [28]:
from sklearn.manifold import TSNE

In [29]:
model = TSNE(n_components=2, random_state=0)

In [30]:
#np.set_printoptions(suppress=True)


In [31]:
#vectors = model.fit_transform(vectors)